name: user_repository
description: User Repository
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  restaurant_repository:
    path: ../restaurant_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
