name: yelp_api
description: Yelp API package
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  flutter:
    sdk: flutter
  json_annotation: ^4.1.0
dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.4
  mocktail: ^0.2.0
