name: restaurant_repository
description: Restaurant repository package
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  yelp_api:
    path: ../yelp_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
