name: restaurants_repository
description: Package to manage the Restaurants domain
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  api_client:
    path: ../api_client
  build_runner: ^2.4.8
  json_annotation: ^4.8.1

dev_dependencies:
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
